# Generated by Django 6.0.4 on 2026-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('hours_played', models.PositiveIntegerField(default=0, verbose_name='Часов сыграно')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Увлечение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🎮', max_length=10, verbose_name='Иконка (эмодзи)')),
            ],
            options={
                'verbose_name': 'Увлечение',
                'verbose_name_plural': 'Увлечения',
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Скриншот')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Подпись к картинке')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Скриншот галереи',
                'verbose_name_plural': 'Скриншоты галереи',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок совета')),
                ('content', models.TextField(verbose_name='Текст совета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='main.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Совет по игре',
                'verbose_name_plural': 'Советы по играм',
            },
        ),
    ]
